// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.0.40152
//    <NameSpace>KasperskyLab.Ipm.Common.Content.Info</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>None</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace IPMATFramework.ContentInfo
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IpmContentInfo")]
    public partial class IpmContentInfo
    {

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ContentType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentTypeInfoType[] ContentTypeList { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Content", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentInfoType[] ContentList { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContentTypeInfoType")]
    public partial class ContentTypeInfoType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SingleInstance { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SubscriptionAdditionalInfoType")]
    public partial class SubscriptionAdditionalInfoType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfoSchemeId { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalInfoString", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AdditionalInfoStrings { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalInfoInteger", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RangeValueType[] AdditionalInfoIntegers { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RangeValueType")]
    public partial class RangeValueType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinValue { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SubscriptionLicenseInfoType")]
    public partial class SubscriptionLicenseInfoType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DateTimeRangeType SubscriptionExpirationDateRange { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionEndDate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubscriptionEndDateTypeEnum[] SubscriptionEndDate { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionState", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubscriptionStateEnum[] SubscriptionState { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionStateReason", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubscriptionStateReasonEnum[] SubscriptionStateReason { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubscriptionAdditionalInfoType AdditionalSchemeInfo { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DateTimeRangeType")]
    public partial class DateTimeRangeType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime To { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    public enum SubscriptionEndDateTypeEnum
    {

        /// <remarks/>
        NotDefined,

        /// <remarks/>
        Unlimited,

        /// <remarks/>
        Limited,

        /// <remarks/>
        Paused,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    public enum SubscriptionStateEnum
    {

        /// <remarks/>
        Active,

        /// <remarks/>
        Paused,

        /// <remarks/>
        SoftCancelled,

        /// <remarks/>
        HardCancelled,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    public enum SubscriptionStateReasonEnum
    {

        /// <remarks/>
        Undefined,

        /// <remarks/>
        ProviderInitiated,

        /// <remarks/>
        CreditCardAuthFailed,

        /// <remarks/>
        CustomerInitiated,

        /// <remarks/>
        CreditCardAuthSuccess,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationLicenseInfoType")]
    public partial class ApplicationLicenseInfoType
    {

        [System.Xml.Serialization.XmlElementAttribute("LicenseType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LicenseType { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("LicenseStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LicenseStatusEnum[] LicenseStatus { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("LicenseTerm", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LicenseTerm { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("OrderNumber", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] OrderNumber { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("PartNumber", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartNumber { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("PartnerName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartnerName { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("PartnerOrderNumber", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartnerOrderNumber { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("PartnerCountry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartnerCountry { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("AdditionalLicenseInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AdditionalLicenseInfo { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("CustomerName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CustomerName { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DateTimeRangeType LicenseExpirationDateRange { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SubscriptionLicenseInfoType SubscriptionLicenseInfo { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> InGracePeriod { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InGracePeriodSpecified
        {
            get
            {
                return InGracePeriod.HasValue;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    public enum LicenseStatusEnum
    {

        /// <remarks/>
        Blocked,

        /// <remarks/>
        Limited,

        /// <remarks/>
        Valid,

        /// <remarks/>
        TrialResetDetected,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationLocalizationType")]
    public partial class ApplicationLocalizationType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alphabet { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "VersionValueType")]
    public partial class VersionValueType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Minor { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Major { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Build { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compilation { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "VersionRangeType")]
    public partial class VersionRangeType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VersionValueType MinVersion { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VersionValueType MaxVersion { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OperationSystemType")]
    public partial class OperationSystemType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformTypeEnum Platform { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VersionRangeType OsVersionRange { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    public enum PlatformTypeEnum
    {

        /// <remarks/>
        Windows,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Windows Mobile")]
        WindowsMobile,

        /// <remarks/>
        Osx,

        /// <remarks/>
        Android,

        /// <remarks/>
        iOs,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationVersionType")]
    public partial class ApplicationVersionType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RangeValueType Minor { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RangeValueType Major { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RangeValueType Build { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RangeValueType Compilation { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationType")]
    public partial class ApplicationType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationVersionType ApplicationVersion { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContentFilterListType")]
    public partial class ContentFilterListType
    {

        [System.Xml.Serialization.XmlElementAttribute("Application", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationType[] Application { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("OperationSystem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OperationSystemType[] OperationSystem { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("PpcsId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PpcsId { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("ApplicationLocalization", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationLocalizationType[] ApplicationLocalization { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("RebrandingCode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RebrandingCode { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("ApplicationLicenseInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationLicenseInfoType[] ApplicationLicenseInfo { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("CountryIsoCode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CountryIsoCode { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("UcpStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UcpStatusTypeEnum[] UcpStatus { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsKasperskyFanUser { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKasperskyFanUserSpecified
        {
            get
            {
                return IsKasperskyFanUser.HasValue;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    public enum UcpStatusTypeEnum
    {

        /// <remarks/>
        Disabled,

        /// <remarks/>
        Enabled,

        /// <remarks/>
        Connected,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContentInfoType")]
    public partial class ContentInfoType
    {

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxDownloadCountPerDay { get; set; }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentUrl { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Filter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentFilterListType[] IncludeContentFilterList { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Filter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentFilterListType[] ExcludeContentFilterList { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContentFiltersType")]
    public partial class ContentFiltersType
    {

        [System.Xml.Serialization.XmlElementAttribute("Filter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentFilterListType[] Filter { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AdditionalInfoStringsType")]
    public partial class AdditionalInfoStringsType
    {

        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfoString", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AdditionalInfoString { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AdditionalInfoIntegerType")]
    public partial class AdditionalInfoIntegerType
    {

        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfoInteger", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RangeValueType[] AdditionalInfoInteger { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContentTypeList")]
    public partial class ContentTypeList
    {

        [System.Xml.Serialization.XmlElementAttribute("ContentType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentTypeInfoType[] ContentType { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContentList")]
    public partial class ContentList
    {

        [System.Xml.Serialization.XmlElementAttribute("Content", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ContentInfoType[] Content { get; set; }
    }
}
